#!/bin/bash

KEYBINDINGS_FILE="$HOME/.config/hypr/hyprland_keybindings.conf"
PROGRAMMS_FILE="$HOME/.config/hypr/hyprland_programs.conf"

# TRANSLATION_LIST is used to replace the variables of programms used in the Hyprland config file with their actual commands.
TRANSLATION_LIST=$(grep '^\$' "$PROGRAMMS_FILE" | sed -e 's/[[:space:]]+/ /g' -e 's/ = /:/g')

# SHORTCUT_LIST stores the formatted keybindings from the Hyprland config file. 
SHORTCUT_LIST=$(grep "bind=" "$KEYBINDINGS_FILE" | \
	sed -E	-e 's/[[:space:]]+/ /g' \
			-e 's/ *bind= *//' \
			-e 's/, /,/g' \
			-e 's/ *# */,/g')

# TABLE is the formatted output for rofi
TABLE=$(echo "$SHORTCUT_LIST" | awk -F ',' '{print $1" "$2"@:"$NF}' | column -s '@' -t)
SELECTED=$(echo "$TABLE" | rofi -i -dmenu -p "")
# Remove description from SELECTED item
SELECTED=$(echo "$SELECTED" | awk -F ':' '{print $1}' | sed 's/ *$//')

# First sed replacement replaces the first "," per line with " " in order to match with the selected output.
COMMAND=$(echo "$SHORTCUT_LIST" | sed 's/,/ /' | grep "$SELECTED" | awk -F ',' '{print $2" "$3}')

# Replace variables
if [[ -n $(echo "$COMMAND" | grep -F "$") ]]; then
	TO_REPLACE=$(echo "$COMMAND" | awk -F '$' '{print "$"$2}')
	REPLACEMENT=$(echo "$TRANSLATION_LIST" | grep "$TO_REPLACE" | awk -F ':' '{print $2}')
	COMMAND=$(echo "$COMMAND" | sed "s/$TO_REPLACE/$REPLACEMENT/")
fi

if [[ $COMMAND == exec* ]]; then
    eval "$COMMAND"
else
    hyprctl dispatch "$COMMAND"
fi
